s#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>
#include <mpi.h>
#include <math.h>

// generated by gui apps
#define PARTITION_WIDTH 12
#define PARTITION_HEIGHT 12
#define BOUNDARY_LEFT 10
#define BOUNDARY_RIGHT -10
#define BOUNDARY_TOP 30
#define BOUNDARY_BOTTOM 200
#define ERROR_MARGIN 1e-9
#define STEP_MAX 1e3

double **element_final, temp;
unsigned int step=0, divergence=1;
struct timeval start_time, stop_time;
int i, j, k, i_min, i_max, j_min, j_max;

int main(int argc, char *argv[]){
	element_final = malloc(sizeof(double*)*PARTITION_HEIGHT);
	for (i=0; i<PARTITION_HEIGHT; i++){
		element_final[i] = malloc(sizeof(double)*PARTITION_WIDTH);
		}
	
	// assigning boundary values
	for (i=0; i<PARTITION_HEIGHT; i++){
		element_final[i][0] = BOUNDARY_LEFT;
		element_final[i][PARTITION_WIDTH-1] = BOUNDARY_RIGHT;
		}
	for (i=0; i<PARTITION_WIDTH; i++){
		element_final[0][i] = BOUNDARY_TOP;
		element_final[PARTITION_HEIGHT-1][i] = BOUNDARY_BOTTOM;
		}
	
	gettimeofday(&start_time,NULL);
	printf("bagiempat-single: start = %d.%d\n",start_time.tv_sec,start_time.tv_usec);
	
// do the actual work here
while(divergence && (step<STEP_MAX)){
	divergence=0;
	step++;
	for (j=1; j<PARTITION_HEIGHT-1; j++){
		for (i=1; i<PARTITION_WIDTH-1; i++){
			temp=0.25*(element_final[j-1][i]+element_final[j][i-1]+\
				element_final[j+1][i]+element_final[j][i+1]);
			if (fabs(temp-element_final[j][i])>ERROR_MARGIN){
				divergence=1;
				element_final[j][i]=temp;
				}
			}
		}
	}

// finish, outputs
	gettimeofday(&stop_time,NULL);
	printf("bagiempat: finish = %d.%d\n",stop_time.tv_sec,stop_time.tv_usec);
	printf("bagiempat: elapsed = %f sec\n",stop_time.tv_sec-start_time.tv_sec+\
		(double)(stop_time.tv_usec-start_time.tv_usec)/1000000);
	for(j=0; j<PARTITION_HEIGHT; j++){
		for(i=0; i<PARTITION_WIDTH; i++){
			printf("%.6f;",element_final[j][i]);
			}
		printf("\n");
		}	
	

return(0);
}
